AWSTemplateFormatVersion: '2010-09-09'
Description: 'OpenSearch Serverless Collection with Security Configuration'

Parameters:
  
Resources:
  # Data Access Policy
  OpenSearchAccessPolicy:
    Type: 'AWS::OpenSearchServerless::AccessPolicy'
    Properties:
      Name: access-policy
      Description: 'Data access policy for OpenSearch Serverless'
      Policy: !Sub |
        [{
          "Rules":[
            {
              "Resource":["collection/my-collection*"],
              "Permission":[
                "aoss:CreateCollection",
                "aoss:DeleteCollection",
                "aoss:UpdateCollection",
                "aoss:DescribeCollection",
                "aoss:ReadDocument",
                "aoss:WriteDocument",
                "aoss:UpdateCollectionSecurity"
              ],
              "ResourceType":"collection"
            }
          ],
          "Principal":["arn:aws:iam::${AWS::AccountId}:role/YourIAMRole"]
        }]

  # OpenSearch Serverless Collection
  OpenSearchCollection:
    Type: 'AWS::OpenSearchServerless::Collection'
    DependsOn: 
      - OpenSearchAccessPolicy
    Properties:
      Name: my-collection
      Description: 'My OpenSearch Serverless Collection'
      Type: SEARCH # Can be SEARCH, TIMESERIES, or VECTORSEARCH
      StandbyReplicas: DISABLED # Can be ENABLED or DISABLED
      # Configure capacity limits
      CollectionCapacityLimits:
        MaximumUnitCount: 20 # Maximum OCUs (OpenSearch Compute Units)
        MinimumUnitCount: 2  # Minimum OCUs
      # Configure retention settings if needed
      RetentionPeriod:
        Period: 7
        Unit: DAYS

Outputs:
  CollectionId:
    Description: 'Collection ID'
    Value: !Ref OpenSearchCollection
  
  CollectionEndpoint:
    Description: 'Collection Endpoint'
    Value: !GetAtt OpenSearchCollection.CollectionEndpoint
