AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template for Knowledge base with Amazon Opensearch Serverless vector database.

Parameters:
  KnowledgeBaseName:
    Type: String
    Description: The name of the knowledge base.
  KnowledgeBaseDescription:
    Type: String
    Description: The description of the knowledge base.
  DataSourceName:
    Type: String
    Description: The name of the data source.
  DataSourceDescription:
    Type: String
    Description: The description of the data source.
  KnowledgeBaseBucketName:
    Type: String
    Description: 'Name for the KnowledgeBase Documents'
    AllowedPattern: ^[a-z0-9][a-z0-9.-]*[a-z0-9]$
    MinLength: 3
    MaxLength: 63
    ConstraintDescription: 'Bucket name must be between 3 and 63 characters, start and end with a lowercase letter or number, and can contain lowercase letters, numbers, hyphens, and periods'
  KnowledgeBaseMetaDataBucketName:
    Type: String
    Description: 'Name for the KnowledgeBase MetaData'
    AllowedPattern: ^[a-z0-9][a-z0-9.-]*[a-z0-9]$
    MinLength: 3
    MaxLength: 63
    ConstraintDescription: 'Bucket name must be between 3 and 63 characters, start and end with a lowercase letter or number, and can contain lowercase letters, numbers, hyphens, and periods'

Resources:
  S3s:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        KnowledgeBaseBucketName: !Ref KnowledgeBaseBucketName
        KnowledgeBaseMetaDataBucketName: !Ref KnowledgeBaseMetaDataBucketName
      TemplateURL: https://milbank-demo-cfts.s3.us-east-1.amazonaws.com/s3.yaml
      #TemplateURL: !Sub https://${SaaSBoostBucket}.s3.${AWS::Region}.${AWS::URLSuffix}/saas-boost-web.yaml
      TimeoutInMinutes: 5
  IAMs:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        KnowledgeBaseBucketArn: !GetAtt S3s.Outputs.KnowledgeBaseBucketArn
            #!Ref KnowledgeBaseBucketArn
        KnowledgeBaseMetaDataBucketArn: !GetAtt S3s.Outputs.KnowledgeBaseMetaDataBucketArn
      TemplateURL: https://milbank-demo-cfts.s3.us-east-1.amazonaws.com/iam.yaml
      TimeoutInMinutes: 5
  

