AWSTemplateFormatVersion: "2010-09-09"
Description: A sample root template for Knowledge base with Amazon Opensearch Serverless vector database supporting resources.

Parameters:
  CloudformationBucketName:
    Type: String
    Description: 'Name for the Cloudformation Files Bucket'
    AllowedPattern: ^[a-z0-9][a-z0-9.-]*[a-z0-9]$
    MinLength: 3
    MaxLength: 63
    ConstraintDescription: 'Bucket name must be between 3 and 63 characters, start and end with a lowercase letter or number, and can contain lowercase letters, numbers, hyphens, and periods'
  KnowledgeBaseBucketName:
    Type: String
    Description: 'Name for the KnowledgeBase Documents'
    AllowedPattern: ^[a-z0-9][a-z0-9.-]*[a-z0-9]$
    MinLength: 3
    MaxLength: 63
    ConstraintDescription: 'Bucket name must be between 3 and 63 characters, start and end with a lowercase letter or number, and can contain lowercase letters, numbers, hyphens, and periods'
  KnowledgeBaseMetaDataBucketName:
    Type: String
    Description: 'Name for the KnowledgeBase MetaData'
    AllowedPattern: ^[a-z0-9][a-z0-9.-]*[a-z0-9]$
    MinLength: 3
    MaxLength: 63
    ConstraintDescription: 'Bucket name must be between 3 and 63 characters, start and end with a lowercase letter or number, and can contain lowercase letters, numbers, hyphens, and periods'

Resources:
  S3s:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        KnowledgeBaseBucketName: !Ref KnowledgeBaseBucketName
        KnowledgeBaseMetaDataBucketName: !Ref KnowledgeBaseMetaDataBucketName
      TemplateURL: !Sub https://${CloudformationBucketName}.s3.${AWS::Region}.amazonaws.com/s3.yaml
      TimeoutInMinutes: 10
  IAMs:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3s
    Properties:
      Parameters:
        KnowledgeBaseBucketArn: !GetAtt S3s.Outputs.KnowledgeBaseBucketArn
        KnowledgeBaseMetaDataBucketArn: !GetAtt S3s.Outputs.KnowledgeBaseMetaDataBucketArn
      TemplateURL: !Sub https://${CloudformationBucketName}.s3.${AWS::Region}.amazonaws.com/iam.yaml
      TimeoutInMinutes: 10
  Lambdas:
    Type: AWS::CloudFormation::Stack
    DependsOn: [S3s, IAMs]
    Properties:
      TemplateURL: !Sub https://${CloudformationBucketName}.s3.${AWS::Region}.amazonaws.com/lambda.yaml
      TimeoutInMinutes: 10

